// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3Cufx_BbnsDiMnNLNfWBBl0zoRYKtwQ',
    appId: '1:49264180262:web:4b26eb90dd09fe3220fae7',
    messagingSenderId: '49264180262',
    projectId: 'burntech-b8a21',
    authDomain: 'burntech-b8a21.firebaseapp.com',
    storageBucket: 'burntech-b8a21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWKta8LjGD2MaUfoFXxE84LrreiPhke4',
    appId: '1:49264180262:android:a6c4706b2d644fce20fae7',
    messagingSenderId: '49264180262',
    projectId: 'burntech-b8a21',
    storageBucket: 'burntech-b8a21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARR5m2L7LmrnFFCI367eu7Wz5xyqIFWmo',
    appId: '1:49264180262:ios:6f8df589cd3742f020fae7',
    messagingSenderId: '49264180262',
    projectId: 'burntech-b8a21',
    storageBucket: 'burntech-b8a21.firebasestorage.app',
    iosBundleId: 'com.example.burnTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARR5m2L7LmrnFFCI367eu7Wz5xyqIFWmo',
    appId: '1:49264180262:ios:6f8df589cd3742f020fae7',
    messagingSenderId: '49264180262',
    projectId: 'burntech-b8a21',
    storageBucket: 'burntech-b8a21.firebasestorage.app',
    iosBundleId: 'com.example.burnTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx3Cufx_BbnsDiMnNLNfWBBl0zoRYKtwQ',
    appId: '1:49264180262:web:896e64a1dd14f49420fae7',
    messagingSenderId: '49264180262',
    projectId: 'burntech-b8a21',
    authDomain: 'burntech-b8a21.firebaseapp.com',
    storageBucket: 'burntech-b8a21.firebasestorage.app',
  );
}
